<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Taller2012BaseBundleEntityPersonaProxy extends \Taller2012\BaseBundle\Entity\Persona implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setApellido($apellido)
    {
        $this->__load();
        return parent::setApellido($apellido);
    }

    public function getApellido()
    {
        $this->__load();
        return parent::getApellido();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setDni($dni)
    {
        $this->__load();
        return parent::setDni($dni);
    }

    public function getDni()
    {
        $this->__load();
        return parent::getDni();
    }

    public function setNacimiento($nacimiento)
    {
        $this->__load();
        return parent::setNacimiento($nacimiento);
    }

    public function getNacimiento()
    {
        $this->__load();
        return parent::getNacimiento();
    }

    public function setDomicilio($domicilio)
    {
        $this->__load();
        return parent::setDomicilio($domicilio);
    }

    public function getDomicilio()
    {
        $this->__load();
        return parent::getDomicilio();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setCuil($cuil)
    {
        $this->__load();
        return parent::setCuil($cuil);
    }

    public function getCuil()
    {
        $this->__load();
        return parent::getCuil();
    }

    public function setNacionalidad($nacionalidad)
    {
        $this->__load();
        return parent::setNacionalidad($nacionalidad);
    }

    public function getNacionalidad()
    {
        $this->__load();
        return parent::getNacionalidad();
    }

    public function setNroalumno($nroalumno)
    {
        $this->__load();
        return parent::setNroalumno($nroalumno);
    }

    public function getNroalumno()
    {
        $this->__load();
        return parent::getNroalumno();
    }

    public function setNroprofesor($nroprofesor)
    {
        $this->__load();
        return parent::setNroprofesor($nroprofesor);
    }

    public function getNroprofesor()
    {
        $this->__load();
        return parent::getNroprofesor();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setIdlocalidad(\Taller2012\BaseBundle\Entity\Localidad $idlocalidad)
    {
        $this->__load();
        return parent::setIdlocalidad($idlocalidad);
    }

    public function getIdlocalidad()
    {
        $this->__load();
        return parent::getIdlocalidad();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'apellido', 'nombre', 'dni', 'nacimiento', 'domicilio', 'email', 'telefono', 'cuil', 'nacionalidad', 'nroalumno', 'nroprofesor', 'id', 'idlocalidad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}