<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Taller2012BaseBundleEntityCohorteProxy extends \Taller2012\BaseBundle\Entity\Cohorte implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setAno($ano)
    {
        $this->__load();
        return parent::setAno($ano);
    }

    public function getAno()
    {
        $this->__load();
        return parent::getAno();
    }

    public function setEdicion($edicion)
    {
        $this->__load();
        return parent::setEdicion($edicion);
    }

    public function getEdicion()
    {
        $this->__load();
        return parent::getEdicion();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setIdplan(\Taller2012\BaseBundle\Entity\Plan $idplan)
    {
        $this->__load();
        return parent::setIdplan($idplan);
    }

    public function getIdplan()
    {
        $this->__load();
        return parent::getIdplan();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'ano', 'edicion', 'id', 'idplan');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}