<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Taller2012BaseBundleEntityPlanProxy extends \Taller2012\BaseBundle\Entity\Plan implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setNresol($nresol)
    {
        $this->__load();
        return parent::setNresol($nresol);
    }

    public function getNresol()
    {
        $this->__load();
        return parent::getNresol();
    }

    public function setAnoresol($anoresol)
    {
        $this->__load();
        return parent::setAnoresol($anoresol);
    }

    public function getAnoresol()
    {
        $this->__load();
        return parent::getAnoresol();
    }

    public function setCantoptativ($cantoptativ)
    {
        $this->__load();
        return parent::setCantoptativ($cantoptativ);
    }

    public function getCantoptativ()
    {
        $this->__load();
        return parent::getCantoptativ();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setIdcarrera(\Taller2012\BaseBundle\Entity\Carrera $idcarrera)
    {
        $this->__load();
        return parent::setIdcarrera($idcarrera);
    }

    public function getIdcarrera()
    {
        $this->__load();
        return parent::getIdcarrera();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nresol', 'anoresol', 'cantoptativ', 'id', 'idcarrera');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}