<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Taller2012BaseBundleEntityCursaProxy extends \Taller2012\BaseBundle\Entity\Cursa implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setNotafinal($notafinal)
    {
        $this->__load();
        return parent::setNotafinal($notafinal);
    }

    public function getNotafinal()
    {
        $this->__load();
        return parent::getNotafinal();
    }

    public function setRegularidad($regularidad)
    {
        $this->__load();
        return parent::setRegularidad($regularidad);
    }

    public function getRegularidad()
    {
        $this->__load();
        return parent::getRegularidad();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setIdinstancia(\Taller2012\BaseBundle\Entity\Instancia $idinstancia)
    {
        $this->__load();
        return parent::setIdinstancia($idinstancia);
    }

    public function getIdinstancia()
    {
        $this->__load();
        return parent::getIdinstancia();
    }

    public function setIdpersona(\Taller2012\BaseBundle\Entity\Persona $idpersona)
    {
        $this->__load();
        return parent::setIdpersona($idpersona);
    }

    public function getIdpersona()
    {
        $this->__load();
        return parent::getIdpersona();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'notafinal', 'regularidad', 'id', 'idinstancia', 'idpersona');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}