<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Taller2012BaseBundleEntityInstanciaProxy extends \Taller2012\BaseBundle\Entity\Instancia implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setFechainicio($fechainicio)
    {
        $this->__load();
        return parent::setFechainicio($fechainicio);
    }

    public function getFechainicio()
    {
        $this->__load();
        return parent::getFechainicio();
    }

    public function setCantclases($cantclases)
    {
        $this->__load();
        return parent::setCantclases($cantclases);
    }

    public function getCantclases()
    {
        $this->__load();
        return parent::getCantclases();
    }

    public function setPorcentajeasis($porcentajeasis)
    {
        $this->__load();
        return parent::setPorcentajeasis($porcentajeasis);
    }

    public function getPorcentajeasis()
    {
        $this->__load();
        return parent::getPorcentajeasis();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setIdcurso(\Taller2012\BaseBundle\Entity\Curso $idcurso)
    {
        $this->__load();
        return parent::setIdcurso($idcurso);
    }

    public function getIdcurso()
    {
        $this->__load();
        return parent::getIdcurso();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'fechainicio', 'cantclases', 'porcentajeasis', 'id', 'idcurso');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}